In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
data = pd.read_csv("insurance.csv")
data.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data[['age','affordibility']],data.bought_insurance,test_size=0.2, random_state=25)

In [4]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [5]:
data_train = X_train_scaled.values
data_test = X_test_scaled.values

y_train = np.array(y_train).reshape(y_train.shape[0] , 1)
y_test = np.array(y_test).reshape(y_test.shape[0] , 1)

In [6]:
data_pass_test = X_test.copy()
data_pass_test = data_pass_test.values
data_pass_test = np.vstack((np.ones((data_pass_test.shape[0] , )) , data_pass_test.T)).T
data_pass_test

array([[ 1., 47.,  1.],
       [ 1., 18.,  1.],
       [ 1., 26.,  0.],
       [ 1., 28.,  1.],
       [ 1., 49.,  1.],
       [ 1., 61.,  1.]])

In [7]:
print(data_train)
print(y_train)

[[0.22 1.  ]
 [0.29 0.  ]
 [0.55 0.  ]
 [0.58 1.  ]
 [0.5  1.  ]
 [0.18 1.  ]
 [0.54 1.  ]
 [0.25 0.  ]
 [0.21 1.  ]
 [0.52 0.  ]
 [0.6  0.  ]
 [0.25 0.  ]
 [0.56 1.  ]
 [0.46 1.  ]
 [0.62 1.  ]
 [0.19 0.  ]
 [0.27 0.  ]
 [0.45 1.  ]
 [0.4  1.  ]
 [0.55 1.  ]
 [0.23 1.  ]
 [0.46 1.  ]]
[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]]


In [8]:
print("shape (x_train) : " , data_train.shape)
print("shape (y_train) : " , y_train.shape)
print("shape (y_train) : " , data_test.shape)
print("shape (y_test) : " , y_test.shape)

shape (x_train) :  (22, 2)
shape (y_train) :  (22, 1)
shape (y_train) :  (6, 2)
shape (y_test) :  (6, 1)


In [9]:
data_train = np.vstack((np.ones((data_train.shape[0] , )) , data_train.T)).T
data_test = np.vstack((np.ones((data_test.shape[0] , )) , data_test.T)).T

In [10]:
data_train[:3]

array([[1.  , 0.22, 1.  ],
       [1.  , 0.29, 0.  ],
       [1.  , 0.55, 0.  ]])

In [11]:
def sigmoid(x) :
      
    return 1 / (1 + math.exp(-x))

In [12]:
def prediction_function(x , val) :
    
    pred = np.dot(x , val)
        
    return sigmoid(pred)

# def prediction_function(x , val) :
    
#     pred = np.dot(x , val)
        
#     return sigmoid(pred)

In [13]:
def sigmoid_numpy(X):
    
    return 1/(1 + np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [14]:
def log_loss(y_true, y_predicted) :
    
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [15]:
def gradient_descent(data_train , y_true, epochs, loss_thresold) :

    rate = 0.5

    m = y_true.size

    theta = np.zeros((data_train.shape[1] , 1))
    
    for i in range(epochs) :
        
        weighted_sum = np.dot(data_train , theta)
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        d_theta = (1/m)*np.dot(data_train.T , y_predicted-y_true)

        theta = theta - rate * d_theta

#         print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

#         if loss<=loss_thresold:
#             break

    return theta

In [16]:
val = gradient_descent(data_train , y_train , 59000 , 0.4631)

In [17]:
print(val)

[[-5.7643138 ]
 [10.99078038]
 [ 1.88869267]]


In [22]:
prediction_function([1 , 0.25 , 0] , val)

0.046680717024797175