In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
x_train = np.array([[0,0,1],
                    [1,1,1],
                    [1,0,1],
                    [0,1,1]])

y_train = np.array([[0,1,1,0]]).T

In [3]:
x_train = np.vstack((np.ones((x_train.shape[0] , )) , x_train.T)).T

In [4]:
print("DATA FOR TRAINING\n")
print(x_train)
print("\nLABELS\n")
print(y_train)

DATA FOR TRAINING

[[1. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 0. 1.]
 [1. 0. 1. 1.]]

LABELS

[[0]
 [1]
 [1]
 [0]]


In [5]:
def sigmoid(x) :
      
    return 1 / (1 + math.exp(-x))

In [6]:
def prediction_function(x , val) :
    
    pred = np.dot(x , val)
        
    return sigmoid(pred)

In [7]:
def sigmoid_numpy(X):
    
    return 1/(1 + np.exp(-X))

In [8]:
def log_loss(y_true, y_predicted) :
    
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [9]:
def gradient_descent(data_train , y_true, epochs) :

    rate = 0.5

    m = y_true.size
    
    theta = np.zeros((data_train.shape[1] , 1))
    
    for i in range(epochs) :
        
        weighted_sum = np.dot(data_train , theta)
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        d_theta = (1/m)*np.dot(data_train.T , y_predicted-y_true)

        theta = theta - rate * d_theta

        print (f'Epoch : {i}  ,  loss : {loss}')

    return theta

In [10]:
val = gradient_descent(x_train , y_train , 1000)

Epoch : 0  ,  loss : 0.6931471805599453
Epoch : 1  ,  loss : 0.6628731079385571
Epoch : 2  ,  loss : 0.6357649033875103
Epoch : 3  ,  loss : 0.6108387543336418
Epoch : 4  ,  loss : 0.5875972006456284
Epoch : 5  ,  loss : 0.5657706658654995
Epoch : 6  ,  loss : 0.5451964605384964
Epoch : 7  ,  loss : 0.525762942590944
Epoch : 8  ,  loss : 0.5073838862639481
Epoch : 9  ,  loss : 0.4899867206274684
Epoch : 10  ,  loss : 0.4735071033979414
Epoch : 11  ,  loss : 0.4578863773627725
Epoch : 12  ,  loss : 0.44307033290878084
Epoch : 13  ,  loss : 0.42900855928965087
Epoch : 14  ,  loss : 0.4156540597698686
Epoch : 15  ,  loss : 0.4029629846860768
Epoch : 16  ,  loss : 0.39089441773209144
Epoch : 17  ,  loss : 0.37941018746750865
Epoch : 18  ,  loss : 0.3684746924375504
Epoch : 19  ,  loss : 0.35805473546240213
Epoch : 20  ,  loss : 0.3481193656704241
Epoch : 21  ,  loss : 0.338639728018357
Epoch : 22  ,  loss : 0.32958892041027404
Epoch : 23  ,  loss : 0.32094185856721474
Epoch : 24  ,  loss :

Epoch : 248  ,  loss : 0.03855422481626709
Epoch : 249  ,  loss : 0.038395769538955876
Epoch : 250  ,  loss : 0.038238587464267434
Epoch : 251  ,  loss : 0.03808266350018631
Epoch : 252  ,  loss : 0.0379279827899896
Epoch : 253  ,  loss : 0.037774530707716324
Epoch : 254  ,  loss : 0.03762229285373929
Epoch : 255  ,  loss : 0.03747125505043828
Epoch : 256  ,  loss : 0.037321403337971154
Epoch : 257  ,  loss : 0.03717272397014118
Epoch : 258  ,  loss : 0.03702520341035661
Epoch : 259  ,  loss : 0.03687882832768225
Epoch : 260  ,  loss : 0.036733585592977805
Epoch : 261  ,  loss : 0.03658946227512369
Epoch : 262  ,  loss : 0.03644644563732987
Epoch : 263  ,  loss : 0.03630452313352691
Epoch : 264  ,  loss : 0.03616368240483619
Epoch : 265  ,  loss : 0.0360239112761182
Epoch : 266  ,  loss : 0.03588519775259587
Epoch : 267  ,  loss : 0.03574753001655204
Epoch : 268  ,  loss : 0.03561089642409888
Epoch : 269  ,  loss : 0.035475285502016826
Epoch : 270  ,  loss : 0.03534068594466214
Epoch :

Epoch : 491  ,  loss : 0.01913910962452416
Epoch : 492  ,  loss : 0.019099239942658948
Epoch : 493  ,  loss : 0.019059534495208107
Epoch : 494  ,  loss : 0.019019992275764362
Epoch : 495  ,  loss : 0.01898061228608753
Epoch : 496  ,  loss : 0.018941393536022484
Epoch : 497  ,  loss : 0.018902335043417554
Epoch : 498  ,  loss : 0.01886343583404442
Epoch : 499  ,  loss : 0.01882469494151845
Epoch : 500  ,  loss : 0.018786111407220196
Epoch : 501  ,  loss : 0.01874768428021796
Epoch : 502  ,  loss : 0.01870941261719116
Epoch : 503  ,  loss : 0.01867129548235466
Epoch : 504  ,  loss : 0.018633331947383817
Epoch : 505  ,  loss : 0.018595521091340644
Epoch : 506  ,  loss : 0.018557862000600868
Epoch : 507  ,  loss : 0.018520353768781434
Epoch : 508  ,  loss : 0.018482995496669673
Epoch : 509  ,  loss : 0.018445786292152173
Epoch : 510  ,  loss : 0.018408725270145768
Epoch : 511  ,  loss : 0.018371811552528212
Epoch : 512  ,  loss : 0.01833504426807013
Epoch : 513  ,  loss : 0.018298422552368

Epoch : 686  ,  loss : 0.013590450235477869
Epoch : 687  ,  loss : 0.013570226581238886
Epoch : 688  ,  loss : 0.013550062631912517
Epoch : 689  ,  loss : 0.013529958124658627
Epoch : 690  ,  loss : 0.013509912798172635
Epoch : 691  ,  loss : 0.013489926392674
Epoch : 692  ,  loss : 0.013469998649895528
Epoch : 693  ,  loss : 0.013450129313072254
Epoch : 694  ,  loss : 0.013430318126930274
Epoch : 695  ,  loss : 0.013410564837676508
Epoch : 696  ,  loss : 0.013390869192987544
Epoch : 697  ,  loss : 0.013371230941999351
Epoch : 698  ,  loss : 0.013351649835296592
Epoch : 699  ,  loss : 0.013332125624902215
Epoch : 700  ,  loss : 0.013312658064267239
Epoch : 701  ,  loss : 0.013293246908260432
Epoch : 702  ,  loss : 0.013273891913158031
Epoch : 703  ,  loss : 0.013254592836634198
Epoch : 704  ,  loss : 0.013235349437750395
Epoch : 705  ,  loss : 0.013216161476945792
Epoch : 706  ,  loss : 0.013197028716027525
Epoch : 707  ,  loss : 0.01317795091816076
Epoch : 708  ,  loss : 0.01315892784

Epoch : 933  ,  loss : 0.009928573954771574
Epoch : 934  ,  loss : 0.009917737709362785
Epoch : 935  ,  loss : 0.009906924978563542
Epoch : 936  ,  loss : 0.009896135686162946
Epoch : 937  ,  loss : 0.009885369756278264
Epoch : 938  ,  loss : 0.009874627113353294
Epoch : 939  ,  loss : 0.009863907682156395
Epoch : 940  ,  loss : 0.009853211387778891
Epoch : 941  ,  loss : 0.009842538155633195
Epoch : 942  ,  loss : 0.009831887911451419
Epoch : 943  ,  loss : 0.009821260581283214
Epoch : 944  ,  loss : 0.009810656091494506
Epoch : 945  ,  loss : 0.00980007436876566
Epoch : 946  ,  loss : 0.00978951534008948
Epoch : 947  ,  loss : 0.009778978932770016
Epoch : 948  ,  loss : 0.00976846507442088
Epoch : 949  ,  loss : 0.009757973692963216
Epoch : 950  ,  loss : 0.009747504716624441
Epoch : 951  ,  loss : 0.00973705807393644
Epoch : 952  ,  loss : 0.009726633693733996
Epoch : 953  ,  loss : 0.009716231505153243
Epoch : 954  ,  loss : 0.009705851437630033
Epoch : 955  ,  loss : 0.00969549342

In [11]:
print(val)

[[-2.23185649]
 [ 9.38233912]
 [-0.22907269]
 [-2.23185649]]


In [12]:
prediction_function([1 , 1 , 0 , 0] , val)

0.9992161295546028